### ISSUE TITLE
[Bug]分支Dev，运行/DebugRun.sh失败

### ISSUE THREAD

**Issue by 1h** [parzulpan/real-live#10]
```
I'm Linux
system_platform:  Linux
system_platform:  Linux
Traceback (most recent call last):
  File "real_live.py", line 36, in <module>
    run()
  File "/home/hu/Code/Python/real-live/src/real-live-desktop/utils/singleton.py", line 24, in inner
    _instance[cls] = cls()
  File "real_live.py", line 29, in run
    main_window = MainWindow()
  File "/home/hu/Code/Python/real-live/src/real-live-desktop/widgets/main_widget.py", line 157, in __init__
    self.vlc_widget = VlcPlayerWidget()
  File "/home/hu/Code/Python/real-live/src/real-live-desktop/widgets/vlc_player_widget.py", line 51, in __init__
    self.set_media_player(args)
  File "/home/hu/Code/Python/real-live/src/real-live-desktop/widgets/vlc_player_widget.py", line 94, in set_media_player
    self.instance = vlc.Instance(*args)
  File "/home/hu/.local/lib/python3.8/site-packages/vlc.py", line 1906, in __new__
    return libvlc_new(len(args), args)
  File "/home/hu/.local/lib/python3.8/site-packages/vlc.py", line 4705, in libvlc_new
    _Cfunction('libvlc_new', ((1,), (1,),), class_result(Instance),
  File "/home/hu/.local/lib/python3.8/site-packages/vlc.py", line 292, in _Cfunction
    raise NameError('no function %r' % (name,))
NameError: no function 'libvlc_new'

```

**Comment by 1h** [comment]
/real-live/src/real-live-desktop/resources/vlc 目录下已经有插件了
`lrwxrwxrwx  1 hu hu   21 10月  1 12:09 libvlc_pulse.so -> libvlc_pulse.so.0.0.0
lrwxrwxrwx  1 hu hu   21 10月  1 12:09 libvlc_pulse.so.0 -> libvlc_pulse.so.0.0.0
-rw-rw-r--  1 hu hu  18K 10月  1 12:09 libvlc_pulse.so.0.0.0
lrwxrwxrwx  1 hu hu   21 10月  1 12:09 libvlc_vdpau.so -> libvlc_vdpau.so.0.0.0
lrwxrwxrwx  1 hu hu   21 10月  1 12:09 libvlc_vdpau.so.0 -> libvlc_vdpau.so.0.0.0
-rw-rw-r--  1 hu hu  23K 10月  1 12:09 libvlc_vdpau.so.0.0.0
lrwxrwxrwx  1 hu hu   26 10月  1 12:09 libvlc_xcb_events.so -> libvlc_xcb_events.so.0.0.0
lrwxrwxrwx  1 hu hu   26 10月  1 12:09 libvlc_xcb_events.so.0 -> libvlc_xcb_events.so.0.0.0
-rw-rw-r--  1 hu hu  15K 10月  1 12:09 libvlc_xcb_events.so.0.0.0
drwxrwxr-x 32 hu hu 4.0K 10月  1 12:09 plugins
drwxrwxr-x  3 hu hu 4.0K 10月  1 12:09 skins
drwxrwxr-x  4 hu hu 4.0K 10月  1 12:25 vlc_3.0.9.2_linux_64
-rwxrwxr-x  1 hu hu  15K 10月  1 12:09 vlc-cache-gen
`

**Comment by parzulpan** [comment]
> ```
> I'm Linux
> system_platform:  Linux
> system_platform:  Linux
> Traceback (most recent call last):
>   File "real_live.py", line 36, in <module>
>     run()
>   File "/home/hu/Code/Python/real-live/src/real-live-desktop/utils/singleton.py", line 24, in inner
>     _instance[cls] = cls()
>   File "real_live.py", line 29, in run
>     main_window = MainWindow()
>   File "/home/hu/Code/Python/real-live/src/real-live-desktop/widgets/main_widget.py", line 157, in __init__
>     self.vlc_widget = VlcPlayerWidget()
>   File "/home/hu/Code/Python/real-live/src/real-live-desktop/widgets/vlc_player_widget.py", line 51, in __init__
>     self.set_media_player(args)
>   File "/home/hu/Code/Python/real-live/src/real-live-desktop/widgets/vlc_player_widget.py", line 94, in set_media_player
>     self.instance = vlc.Instance(*args)
>   File "/home/hu/.local/lib/python3.8/site-packages/vlc.py", line 1906, in __new__
>     return libvlc_new(len(args), args)
>   File "/home/hu/.local/lib/python3.8/site-packages/vlc.py", line 4705, in libvlc_new
>     _Cfunction('libvlc_new', ((1,), (1,),), class_result(Instance),
>   File "/home/hu/.local/lib/python3.8/site-packages/vlc.py", line 292, in _Cfunction
>     raise NameError('no function %r' % (name,))
> NameError: no function 'libvlc_new'
> ```

用的什么Python版本？

**Comment by 1h** [comment]
> > ```
> > I'm Linux
> > system_platform:  Linux
> > system_platform:  Linux
> > Traceback (most recent call last):
> >   File "real_live.py", line 36, in <module>
> >     run()
> >   File "/home/hu/Code/Python/real-live/src/real-live-desktop/utils/singleton.py", line 24, in inner
> >     _instance[cls] = cls()
> >   File "real_live.py", line 29, in run
> >     main_window = MainWindow()
> >   File "/home/hu/Code/Python/real-live/src/real-live-desktop/widgets/main_widget.py", line 157, in __init__
> >     self.vlc_widget = VlcPlayerWidget()
> >   File "/home/hu/Code/Python/real-live/src/real-live-desktop/widgets/vlc_player_widget.py", line 51, in __init__
> >     self.set_media_player(args)
> >   File "/home/hu/Code/Python/real-live/src/real-live-desktop/widgets/vlc_player_widget.py", line 94, in set_media_player
> >     self.instance = vlc.Instance(*args)
> >   File "/home/hu/.local/lib/python3.8/site-packages/vlc.py", line 1906, in __new__
> >     return libvlc_new(len(args), args)
> >   File "/home/hu/.local/lib/python3.8/site-packages/vlc.py", line 4705, in libvlc_new
> >     _Cfunction('libvlc_new', ((1,), (1,),), class_result(Instance),
> >   File "/home/hu/.local/lib/python3.8/site-packages/vlc.py", line 292, in _Cfunction
> >     raise NameError('no function %r' % (name,))
> > NameError: no function 'libvlc_new'
> > ```
> 
> 用的什么Python版本？
python 3.8.2 系统 ubuntu 20.04

**Comment by parzulpan** [comment]
> > > ```
> > > I'm Linux
> > > system_platform:  Linux
> > > system_platform:  Linux
> > > Traceback (most recent call last):
> > >   File "real_live.py", line 36, in <module>
> > >     run()
> > >   File "/home/hu/Code/Python/real-live/src/real-live-desktop/utils/singleton.py", line 24, in inner
> > >     _instance[cls] = cls()
> > >   File "real_live.py", line 29, in run
> > >     main_window = MainWindow()
> > >   File "/home/hu/Code/Python/real-live/src/real-live-desktop/widgets/main_widget.py", line 157, in __init__
> > >     self.vlc_widget = VlcPlayerWidget()
> > >   File "/home/hu/Code/Python/real-live/src/real-live-desktop/widgets/vlc_player_widget.py", line 51, in __init__
> > >     self.set_media_player(args)
> > >   File "/home/hu/Code/Python/real-live/src/real-live-desktop/widgets/vlc_player_widget.py", line 94, in set_media_player
> > >     self.instance = vlc.Instance(*args)
> > >   File "/home/hu/.local/lib/python3.8/site-packages/vlc.py", line 1906, in __new__
> > >     return libvlc_new(len(args), args)
> > >   File "/home/hu/.local/lib/python3.8/site-packages/vlc.py", line 4705, in libvlc_new
> > >     _Cfunction('libvlc_new', ((1,), (1,),), class_result(Instance),
> > >   File "/home/hu/.local/lib/python3.8/site-packages/vlc.py", line 292, in _Cfunction
> > >     raise NameError('no function %r' % (name,))
> > > NameError: no function 'libvlc_new'
> > > ```
> > 
> > 用的什么Python版本？
> python 3.8.2 系统 ubuntu 20.04
> 

建议使用3.6和3.7版本，版本太新，有的库匹配的不是很好。
