### ISSUE TITLE
小白怎么才能把项目运行起来啊！！

### ISSUE THREAD

**Issue by s7liyang** [parzulpan/real-live#2]
我是小白，写个简单教程吧

**Comment by parzulpan** [comment]
可以看readme，Debug使用哈，再不会可以问我 pan parzul 邮箱：parzulpan@gmail.com 签名由 网易邮箱大师 定制 在2020年09月18日 11:22，hiyang 写道： 我是小白，写个简单教程吧 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by s7liyang** [comment]
好的，感谢，我研究研究python

**Comment by yrj-essential** [comment]
我已下载好了依赖，在运行real_live.py时，提示找不到指定的模块，截图如下：
![image](https://user-images.githubusercontent.com/24262359/93573976-63206980-f9ca-11ea-8ab2-2adfcde05e2f.png)
是差了什么dll呢？

**Comment by parzulpan** [comment]
> 我已下载好了依赖，在运行real_live.py时，提示找不到指定的模块，截图如下：
> ![image](https://user-images.githubusercontent.com/24262359/93573976-63206980-f9ca-11ea-8ab2-2adfcde05e2f.png)
> 是差了什么dll呢？

对项目有任何疑问和建议的胡欢迎加入QQ 群 RealLive项目讨论群：893364757

**Comment by wuooyun** [comment]
同样的错误

**Comment by yrj-essential** [comment]
> 同样的错误

我运行起来了，作者更新了新的readme，可以按着上面来。
检查下real-live-dev\src\resources\vlc_3.0.9.2_windows_64是否存在，如果没有的话，将项目的 resources 文件夹里面的 vlc_3.0.9.2_windows_64 文件夹复制到此文件夹中。再次运行就可以启动了
