### ISSUE TITLE
不知道是不是打包错误

### ISSUE THREAD

**Issue by masterbiu** [parzulpan/real-live#3]
![Snipaste_2020-09-19_00-02-27](https://user-images.githubusercontent.com/28528778/93619825-b49d1880-fa0b-11ea-9ba4-edb9da2733e8.png)

**Comment by parzulpan** [comment]
你是用的什么命令打包的？而且应该是在 dist 文件夹里哦

**Comment by masterbiu** [comment]
就你这个文档里的，改了一下icon地址，dist里的运行没有任何反应（双击无反应），build里的就报了这个错

**Comment by parzulpan** [comment]
是用的 `Pyinstaller real_live_windows.spec` 这个命令吗

**Comment by masterbiu** [comment]
`pyinstaller real_live.spec`

**Comment by parzulpan** [comment]
你分支拉错了吧 拉 dev 分支

**Comment by masterbiu** [comment]
是upx的问题，现在包VCRUNTIME140.dll没有被指定在Windows上运行，我重新注册了dll文件还是不行，你有遇到过吗？感觉应该是我这边的问题，我还是先用1.1.0的吧，你有空的话可以发布一个打包好的吗，谢谢
![Snipaste_2020-09-19_14-16-40](https://user-images.githubusercontent.com/28528778/93660554-c40b7880-fa82-11ea-916a-05ac97b8080a.png)

**Comment by parzulpan** [comment]
> 是upx的问题，现在包VCRUNTIME140.dll没有被指定在Windows上运行，我重新注册了dll文件还是不行，你有遇到过吗？感觉应该是我这边的问题，我还是先用1.1.0的吧，你有空的话可以发布一个打包好的吗，谢谢
> ![Snipaste_2020-09-19_14-16-40](https://user-images.githubusercontent.com/28528778/93660554-c40b7880-fa82-11ea-916a-05ac97b8080a.png)

对项目有任何疑问和建议的胡欢迎加入QQ 群 RealLive项目讨论群：893364757
