### ISSUE TITLE
1.3.0有windows的安装包吗？

### ISSUE THREAD

**Issue by zekeyang** [parzulpan/real-live#4]

**Comment by parzulpan** [comment]
我打包下，等会儿更新下。

**Comment by parzulpan** [comment]
> _No description provided._

对项目有任何疑问和建议的胡欢迎加入QQ 群 RealLive项目讨论群：893364757

**Comment by myworksfun** [comment]
然而，所有的平台上均无法访问

**Comment by parzulpan** [comment]
> 然而，所有的平台上均无法访问

获取链接吗？可以贴一下错误详情！

**Comment by haigouCan** [comment]
https://github.com/parzulpan/real-live/releases/download/v1.3.0/real_live_v1.3.0_linux_64.tar.gz
这是网站提供的获取链接，但是是not found的

**Comment by parzulpan** [comment]
> https://github.com/parzulpan/real-live/releases/download/v1.3.0/real_live_v1.3.0_linux_64.tar.gz
> 这是网站提供的获取链接，但是是not found的

明白了，这个网站的链接还没更新，等我更新一下。

**Comment by love2wind** [comment]
打包下桌面版的哦，下载地址是错的哦
