### ISSUE TITLE
Mac 下载哪个release版本以及如何安装啊？

### ISSUE THREAD

**Issue by MetroBear** [parzulpan/real-live#5]
如题，小白暗搓搓问一下。下载了不知道怎么打开
原谅我问了一个蠢蠢的问题

**Comment by parzulpan** [comment]
mac的打包还没上传，这两天我弄一下哈

**Comment by parzulpan** [comment]
> 如题，小白暗搓搓问一下。下载了不知道怎么打开
> 原谅我问了一个蠢蠢的问题

对项目有任何疑问和建议的胡欢迎加入QQ 群 RealLive项目讨论群：893364757

**Comment by kun-qian** [comment]
VLC for MacOS not available.
You must be kidding.

**Comment by parzulpan** [comment]
> VLC for MacOS not available.
> You must be kidding.

hah.This is due to the lack of VLC plug-in under MacOS, you need to move the VLC plug-in by yourself. The current `real-live/plugins/vlc_3.0.9.2_macos_64/` folder is empty. Since my development machine is Debian, I currently We are looking for the VLC plug-in under MacOS, please stay tuned.

**Comment by JasonJunjian** [comment]
MAC安装后 打不开 闪退
