### ISSUE TITLE
Build failure on master branch

### ISSUE THREAD

**Issue by cheney-yan** [parzulpan/real-live#9]
**Describe the bug**
commit 866f678b84a303361144b25396fc441a7b769e09 on master branch.
When running ./DebugRun.sh, it spits:

```
I'm MacOS
system_platform:  Darwin
system_platform:  Darwin
system_platform:  Darwin
system_platform:  Darwin
system_platform:  Darwin
system_platform:  Darwin
Traceback (most recent call last):
  File "real_live.py", line 36, in <module>
    run()
  File "/Users/SonderTALVCF/work/personal/real-live/src/real-live-desktop/utils/singleton.py", line 24, in inner
    _instance[cls] = cls()
  File "real_live.py", line 29, in run
    main_window = MainWindow()
  File "/Users/SonderTALVCF/work/personal/real-live/src/real-live-desktop/widgets/main_widget.py", line 157, in __init__
    self.vlc_widget = VlcPlayerWidget()
  File "/Users/SonderTALVCF/work/personal/real-live/src/real-live-desktop/widgets/vlc_player_widget.py", line 51, in __init__
    self.set_media_player(args)
  File "/Users/SonderTALVCF/work/personal/real-live/src/real-live-desktop/widgets/vlc_player_widget.py", line 108, in set_media_player
    self.media_player.set_nsobject(self.media_player_frame.winId())
  File "/Users/SonderTALVCF/bin/.venv/lib/python3.7/site-packages/vlc.py", line 3709, in set_nsobject
    return libvlc_media_player_set_nsobject(self, drawable)
  File "/Users/SonderTALVCF/bin/.venv/lib/python3.7/site-packages/vlc.py", line 6835, in libvlc_media_player_set_nsobject
    return f(p_mi, drawable)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

**Comment by parzulpan** [comment]
Yes, I understand, this is caused by the lack of VLC plugin. Under MacOS, you need to move the VLC plug-in by yourself. The current `real-live/plugins/vlc_3.0.9.2_macos_64/` folder is empty. You can refer to the `real-live/plugins/vlc_3.0.9.2_linux_64/` folder to configure the `real-live/plugins/vlc_3.0.9.2_macos_64/` folder. I am looking for a VLC plug-in for MacOS. Please pay close attention.

**Comment by parzulpan** [comment]
> **Describe the bug**
> commit [866f678](https://github.com/parzulpan/real-live/commit/866f678b84a303361144b25396fc441a7b769e09) on master branch.
> When running ./DebugRun.sh, it spits:
> 
> ```
> I'm MacOS
> system_platform:  Darwin
> system_platform:  Darwin
> system_platform:  Darwin
> system_platform:  Darwin
> system_platform:  Darwin
> system_platform:  Darwin
> Traceback (most recent call last):
>   File "real_live.py", line 36, in <module>
>     run()
>   File "/Users/SonderTALVCF/work/personal/real-live/src/real-live-desktop/utils/singleton.py", line 24, in inner
>     _instance[cls] = cls()
>   File "real_live.py", line 29, in run
>     main_window = MainWindow()
>   File "/Users/SonderTALVCF/work/personal/real-live/src/real-live-desktop/widgets/main_widget.py", line 157, in __init__
>     self.vlc_widget = VlcPlayerWidget()
>   File "/Users/SonderTALVCF/work/personal/real-live/src/real-live-desktop/widgets/vlc_player_widget.py", line 51, in __init__
>     self.set_media_player(args)
>   File "/Users/SonderTALVCF/work/personal/real-live/src/real-live-desktop/widgets/vlc_player_widget.py", line 108, in set_media_player
>     self.media_player.set_nsobject(self.media_player_frame.winId())
>   File "/Users/SonderTALVCF/bin/.venv/lib/python3.7/site-packages/vlc.py", line 3709, in set_nsobject
>     return libvlc_media_player_set_nsobject(self, drawable)
>   File "/Users/SonderTALVCF/bin/.venv/lib/python3.7/site-packages/vlc.py", line 6835, in libvlc_media_player_set_nsobject
>     return f(p_mi, drawable)
> ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
> ```

Yes, I understand, this is caused by the lack of VLC plugin. Under MacOS, you need to move the VLC plug-in by yourself. The current real-live/plugins/vlc_3.0.9.2_macos_64/ folder is empty. You can refer to the real-live/plugins/vlc_3.0.9.2_linux_64/ folder to configure the real-live/plugins/vlc_3.0.9.2_macos_64/ folder. I am looking for a VLC plug-in for MacOS. Please pay close attention.
